#!/usr/bin/env bash
set -euo pipefail

# compare-upstream.sh
# Compare your digital garden against MaggieAppleton/maggieappleton.com-V3
# Run whenever you want to see what upstream has changed recently.
#
# Usage:
#   scripts/comparison/compare-upstream.sh [output_dir]
# Defaults to writing to scripts/comparison/reports/YYYY-MM-DD

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT_DIR"

WORK_DIR="$(mktemp -d)"
REPORTS_DIR="${1:-$ROOT_DIR/scripts/comparison/reports}"
DATE_STR=$(date +%Y-%m-%d)
REPORT_DIR="$REPORTS_DIR/$DATE_STR"
mkdir -p "$REPORT_DIR"

echo "=> Fetching upstream..."
git fetch upstream --no-tags

echo "=> Exporting archives..."
git archive --format=tar --prefix=maggie-upstream/ upstream/main -o "$WORK_DIR/maggie-upstream.tar"
git archive --format=tar --prefix=my-garden/ HEAD -o "$WORK_DIR/my-garden.tar"
mkdir -p "$WORK_DIR/maggie-upstream" "$WORK_DIR/my-garden"
tar -xf "$WORK_DIR/maggie-upstream.tar" -C "$WORK_DIR/maggie-upstream"
tar -xf "$WORK_DIR/my-garden.tar" -C "$WORK_DIR/my-garden"

echo "=> Generating reports..."

LOCAL_SRC="$WORK_DIR/my-garden/my-garden/src"
UPSTREAM_SRC="$WORK_DIR/maggie-upstream/maggie-upstream/src"
LOCAL_ROOT="$WORK_DIR/my-garden/my-garden"
UPSTREAM_ROOT="$WORK_DIR/maggie-upstream/maggie-upstream"

# 1. Summary
cat > "$REPORT_DIR/summary.md" <<EOF
# Upstream Comparison Report — $DATE_STR

- Local HEAD:  $(git rev-parse --short HEAD) — $(git log -1 --format='%s (%ad)' --date=short HEAD)
- Upstream HEAD: $(git rev-parse --short upstream/main) — $(git log -1 --format='%s (%ad)' --date=short upstream/main)
- Common commit base: None (histories are unrelated; comparison is content-based)

## File counts

| Branch | src files |
|--------|-----------|
| my-garden | $(find "$LOCAL_SRC" -type f 2>/dev/null | wc -l | tr -d ' ') |
| maggie-upstream | $(find "$UPSTREAM_SRC" -type f 2>/dev/null | wc -l | tr -d ' ') |

EOF

# 2. Differences in non-content source code
diff -rq "$LOCAL_SRC" "$UPSTREAM_SRC" > "$REPORT_DIR/src-files.diff.txt" 2>&1 || true

only_local=$(grep -E '^Only in.*my-garden' "$REPORT_DIR/src-files.diff.txt" | sed "s|Only in $LOCAL_SRC/|- |" | sed "s|: |/|" || true)
only_upstream=$(grep -E '^Only in.*maggie-upstream' "$REPORT_DIR/src-files.diff.txt" | sed "s|Only in $UPSTREAM_SRC/|- |" | sed "s|: |/|" || true)
changed_count=$(grep -cE '^Files .* differ' "$REPORT_DIR/src-files.diff.txt" || true)

cat >> "$REPORT_DIR/summary.md" <<EOF
## Source-only files

### Only in your garden

\`\`\`
$only_local
\`\`\`

### Only upstream

\`\`\`
$only_upstream
\`\`\`

## Source files that differ

$changed_count files

Top changed paths:

\`\`\`
$(cut -d' ' -f2,4 "$REPORT_DIR/src-files.diff.txt" 2>/dev/null | sed 's|/.*/my-garden/my-garden/src/||; s|/.*/maggie-upstream/maggie-upstream/src/||' | head -50)
\`\`\`

EOF

# 3. Recent upstream commits (non-content)
cat >> "$REPORT_DIR/summary.md" <<'EOF'
## Recent upstream commits (excluding content)

```
EOF
git log --oneline --format='%h %ad %s' --date=short upstream/main \
  -- . ':(exclude)src/content/**/*' ':(exclude).github/aw/**/*' \
  >> "$REPORT_DIR/summary.md" || true
cat >> "$REPORT_DIR/summary.md" <<'EOF'
```

EOF

# 4. Config / script diffs
mkdir -p "$REPORT_DIR/diffs"
for path in package.json astro.config.mjs tsconfig.json deploy.sh; do
  if [ -f "$LOCAL_ROOT/$path" ] && [ -f "$UPSTREAM_ROOT/$path" ]; then
    diff -u "$LOCAL_ROOT/$path" "$UPSTREAM_ROOT/$path" \
      > "$REPORT_DIR/diffs/${path//\//-}.diff" 2>&1 || true
  fi
done

# 5. Notable component presence quick-reference
cat >> "$REPORT_DIR/summary.md" <<'EOF'
## Notable component presence

Components present only upstream (candidates to consider porting):

EOF
for f in ScrollyTalkSection.astro Accordion.astro GrowthStage.astro MobileMenu.astro GardenFilters.astro GardenHits.astro VersionDropdown.astro; do
  local_file=$(find "$LOCAL_SRC" -name "$f" -print -quit)
  upstream_file=$(find "$UPSTREAM_SRC" -name "$f" -print -quit)
  if [ -z "$local_file" ] && [ -n "$upstream_file" ]; then
    echo "- $f" >> "$REPORT_DIR/summary.md"
  fi
done

cat >> "$REPORT_DIR/summary.md" <<'EOF'

---

*Generated by `scripts/comparison/compare-upstream.sh`*
EOF

rm -rf "$WORK_DIR"
echo "=> Report written to $REPORT_DIR"
